name: docs

on:
  push:
    branches:
      - development

jobs:
  api-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      # - name: Install dependencies
      #   run: make dev
      - name: Setup doc deploy
        run: |
          git config --global user.name Hagar Usama
          git config --global user.email hagar_usama@outlook.com
      - name: install mike
        run: pip install mike 
      - name: deploy version
        run: mike deploy v1 stable